//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Font_Changer {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Windows_Font_Changer.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Değiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string degistir {
            get {
                return ResourceManager.GetString("degistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başarılı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mesajBaslik {
            get {
                return ResourceManager.GetString("mesajBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sıfırla benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sifirla {
            get {
                return ResourceManager.GetString("sifirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yazı Tipi Başarıyla Değiştirildi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yazitipiDegistirMesaj {
            get {
                return ResourceManager.GetString("yazitipiDegistirMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yazı Tipi Başarıyla Sıfırlandı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yazitipiSifirlaMesaj {
            get {
                return ResourceManager.GetString("yazitipiSifirlaMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uyarı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yenidenBaslatBaslik {
            get {
                return ResourceManager.GetString("yenidenBaslatBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Değişikliklerin uygulanabilmesi için Bilgisayarınızın yeniden başlatılması gerekiyor. Şimdi Yeniden Başlatmak ister misiniz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string yenidenBaslatMesaj {
            get {
                return ResourceManager.GetString("yenidenBaslatMesaj", resourceCulture);
            }
        }
    }
}
